export interface CasacionDataModel{
    codigoEstado: string,
    nombreEstado: string,
    codigoProgramacion: string,
    codigoDitrito: string,
    codigoProvincia: string,
    codigoInstancia: string,
    nombreInstancia: string,
    numeroProgramacion: number,
    numeroGrupo: number,
    numeroSecuencia: number,
    numeroConformacion: number,
    numeroUnico: number,
    numeroIncidente: number,
    fechaIngreso: string,
    fechaProgramacion: string,
    numeroExpedienteSala: number,
    codigoLetra: string | null,
    numeroAnioSala: string,
    numeroRecurso: string,
    codigoMotivoIngreso: string,
    nombreMotivoIngreso: string,
    codigoProcedencia: string,
    nombreProcedencia: string,
    numeroOrden: string | null,
    fechaEstado: string,
    codigoArea: string |null,
    numeroSentido: number,
    numeroVotacion: number,
    vocalPonente: string,
    descripcionTipoProgramaAudienciaOrgano: string,
    abreviaturaTipoProgramaAudienciaOrgano: string,
    descripcionProceso: string,
    descripcionActoProcesalJuzgado: string |null,
    numeroFojasJuzgado: string|null,
    descripcionActoProcesalJuzgadoAdicional: string,
    descripcionActoProcesalSala: string,
    numeroFojasSala: number,
    descripcionActoProcesalSalaAdicional: string,
    codigoFalloSala: number,
    descripcionFalloSala: string,
    codigoFalloJuzgado: string | null,
    descripcionFalloJuzgado: string |null
}